### ISSUE TITLE
TextMate bundle throw exception while trying to load resource file

### ISSUE THREAD

**Issue by GauthierPLM** [samdark/intellij-visual-studio-code-dark-plus#6]
The following exception is thrown with version 1.6 (downloaded from Github) on IJ Ultimate 2019.2. It happens at every IDE launch and I guess it's because the TextMate plugin is trying to load a theme that is not meant to be loaded.

```
java.lang.Throwable: Cannot read scheme from /resources/visual_studio_code_dark_plus.xml
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadBundledScheme(SchemeManagerImpl.kt:123)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.loadBundledSchemes(EditorColorsManagerImpl.java:205)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.<init>(EditorColorsManagerImpl.java:150)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:243)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:227)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:75)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:44)
	at com.intellij.openapi.editor.colors.EditorColorsManager.getInstance(EditorColorsManager.java:36)
	at com.intellij.openapi.editor.colors.impl.TextAttributeKeyDefaultsProviderImpl.getDefaultAttributes(TextAttributeKeyDefaultsProviderImpl.java:29)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getDefaultAttributes(TextAttributesKey.java:146)
	at org.jetbrains.plugins.textmate.language.syntax.highlighting.TextMateDefaultColorsProvider.getTextAttributes(TextMateDefaultColorsProvider.java:75)
	at org.jetbrains.plugins.textmate.language.syntax.highlighting.TextMateTheme.initDefaultColors(TextMateTheme.java:40)
	at org.jetbrains.plugins.textmate.language.syntax.highlighting.TextMateTheme.<init>(TextMateTheme.java:34)
	at org.jetbrains.plugins.textmate.language.syntax.highlighting.TextMateTheme.<clinit>(TextMateTheme.java:22)
	at org.jetbrains.plugins.textmate.TextMateServiceImpl.registerTheme(TextMateServiceImpl.java:230)
	at org.jetbrains.plugins.textmate.TextMateServiceImpl.lambda$null$4(TextMateServiceImpl.java:292)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by samdark** [comment]
Any specific plugins or config?

**Comment by samdark** [comment]
Reproduced.

**Comment by samdark** [comment]
The commit that triggered it is https://github.com/samdark/intellij-visual-studio-code-dark-plus/commit/f6ecd55d53acdc8f9fbd187223c8a8d63afa8464. Not sure why though.

**Comment by GauthierPLM** [comment]
Isn't it because the file name does not have an extension but would be supposed to be `visual_studio_code_dark_plus.xml`?

Also, pay attention because the plugin must at least have one dependency tag pointing on the IJ platform, as [explained in documentation](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html). I noticed that your commit deleted the dependency on lang module.

**Comment by samdark** [comment]
> Isn't it because the file name does not have an extension but would be supposed to be visual_studio_code_dark_plus.xml?

No. It adds `.xml` as you can see from exception.

**Comment by samdark** [comment]
> I noticed that your commit deleted the dependency on lang module.

It is still there. What was deleted is part of commented-out boilerplate.

**Comment by samdark** [comment]
https://youtrack.jetbrains.net/issue/IDEA-218133

**Comment by samdark** [comment]
Thanks to Alexander Zolotov, found what was wrong.
